<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Negative</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1df842c4-ab97-40b6-901d-90dffdfda8ed</testSuiteGuid>
   <testCaseLink>
      <guid>cab69fda-8ccb-4e14-b2c7-70c4a1ed53b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Small_Project_1/Navigate_to_url</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bbf0a283-fa78-4265-993d-16467aa6f71a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Small_Project_1/Negative_CreditDebit_Card - 1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90e020b0-3ac5-4824-9e47-2b6231ec30d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd5043ab-8461-4da3-9734-1f3d6b2e4dff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1806a2e3-42de-4a1f-9c07-afc4d607abf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>361a27de-2e59-45ec-aaa7-69c67fef25df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d53ff0f1-e3b3-4df2-a678-38e2a34b7e07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8435201-41c2-4d57-9da5-fa6ab49b9817</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf1d8a66-7f1b-4609-b583-df6c6afa64e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbf66cd6-6db7-45c8-a2ab-c10200892f50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f203bfa-e4a4-4409-97e2-ef74bbcc5473</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b85e9c8-11a5-4d4d-9ae1-c5aea8caff56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Small_Project_1/Navigate_close_url</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
