<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_usersetting</name>
   <tag></tag>
   <elementGuidId>95af15ab-b4f8-4603-8766-fce65bb7ee0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@src='https://www.cilsy.id/template/web/img/drop-down-round-button.png'][count(. | //*[@class = 'icon']) = count(//*[@class = 'icon'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src='https://www.cilsy.id/template/web/img/drop-down-round-button.png']</value>
   </webElementProperties>
</WebElementEntity>
