<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Apk_Foody</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d9068771-e402-4424-8240-d418c10f404c</testSuiteGuid>
   <testCaseLink>
      <guid>70ed794b-1578-463c-8db3-b76f0932ddf1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Foody/TC1_LoginFacebook</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bccaeb47-ab07-4c16-90b7-fda113658040</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1bac220-b0cd-46f1-b296-098391818593</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Foody/TC2_MencariMakanan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c281b5ae-56cf-4e12-807e-fcb7dd9447bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19e711e0-7c8e-4423-8f30-94c04a6737fc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
