<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_issuing_bank</name>
   <tag></tag>
   <elementGuidId>b0b63f16-a0ef-4ede-8301-29bd00e38b12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[src='../../assets/issuing_bank_logo.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[src='../../assets/issuing_bank_logo.png']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>left img-responsive</value>
   </webElementProperties>
</WebElementEntity>
