<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_iframe_issuing_bank</name>
   <tag></tag>
   <elementGuidId>4a4722f3-af7a-492c-8102-1bae4e01931c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>iframe[id='snap-midtrans']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@src='https://api.sandbox.veritrans.co.id/v2/token/rba/redirect/481111-1114-2f11cbf3-8c10-423f-8411-95fd4e0cc07b']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
</WebElementEntity>
