<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_phone_no_credit_debit_card</name>
   <tag></tag>
   <elementGuidId>67eabbdb-06ef-45f8-bfa0-8cab7212ac30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[placeholder='+6281234567890']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[placeholder='+6281234567890']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[placeholder='+6281234567890']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filled</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input[@class='filled']</value>
   </webElementProperties>
</WebElementEntity>
