<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_email_credit_debit_card</name>
   <tag></tag>
   <elementGuidId>d219bfc3-53f8-4161-b058-0edcfc3b0e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[placeholder='budi@utomo.com']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[placeholder='budi@utomo.com']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filled</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[placeholder='budi@utomo.com']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[5]/div[1]/input[@class='filled']</value>
   </webElementProperties>
</WebElementEntity>
